export const union = {
  welcome: '/welcome',
  main: '/main',
  search: '/search',
  auth: '/auth',
  login: '/auth/login',
  signup: '/auth/signup',
  lightLogo: './assets/img/light_logo_kanban.png',
  darkLogo: './assets/img/logo_kanban.png',
  lightBgColor: '#c2cdee',
  darkBgColor: '#00093c',
  lightColor: '#fff',
  darkColor: '#000',
  yellow: 'rgb(247, 248, 170)',
  darkSv: './assets/img/githubSv3.png',
  darkIv: './assets/img/githubIv3.png',
  darkUl: './assets/img/githubUl3.png',
  darkRS: './assets/img/logoRSdark0.png',
  lightSv: './assets/img/githubSv.png',
  lightIv: './assets/img/githubIv.png',
  lightUl: './assets/img/githubUl.png',
  lightRs: './assets/img/rs-school.png',
};
